# Generated by Django 5.1.4 on 2026-03-22 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Invoice Number')),
                ('date', models.DateField(verbose_name='Invoice Date')),
                ('gst_rate', models.PositiveIntegerField(choices=[(0, '0% GST'), (5, '5% GST'), (18, '18% GST')], default=0, verbose_name='GST Rate (%)')),
                ('gst_type', models.CharField(choices=[('INTRA', 'Intra-state'), ('INTER', 'Inter-state')], default='INTRA', max_length=10, verbose_name='GST Type')),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Final', 'Final')], default='Draft', max_length=10)),
                ('invoice_company_name', models.CharField(blank=True, max_length=200, verbose_name='Company Name (Snapshot)')),
                ('invoice_company_address', models.TextField(blank=True, verbose_name='Company Address (Snapshot)')),
                ('invoice_company_mobile', models.CharField(blank=True, max_length=20, verbose_name='Company Mobile (Snapshot)')),
                ('invoice_company_gstin', models.CharField(blank=True, max_length=20, verbose_name='Company GSTIN (Snapshot)')),
                ('invoice_bank_name', models.CharField(blank=True, max_length=200, verbose_name='Bank Name (Snapshot)')),
                ('invoice_bank_account', models.CharField(blank=True, max_length=50, verbose_name='Bank Account (Snapshot)')),
                ('invoice_bank_ifsc', models.CharField(blank=True, max_length=20, verbose_name='Bank IFSC (Snapshot)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, help_text='Description shown on invoice (e.g., destination/material)', verbose_name='Item Description')),
                ('hsn_code', models.CharField(default='996511', max_length=20, verbose_name='HSN Code')),
                ('reverse_charge', models.BooleanField(default=False, verbose_name='Reverse Charge')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Firm Name')),
                ('address', models.TextField(blank=True, verbose_name='Firm Address')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Phone Number')),
                ('gstin', models.CharField(blank=True, max_length=20, verbose_name='GSTIN')),
                ('pan', models.CharField(blank=True, max_length=20, verbose_name='PAN')),
                ('bank_name', models.CharField(blank=True, max_length=200, verbose_name='Bank Name')),
                ('account_number', models.CharField(blank=True, max_length=50, verbose_name='Account Number')),
                ('ifsc_code', models.CharField(blank=True, max_length=20, verbose_name='IFSC Code')),
                ('account_holder_name', models.CharField(blank=True, max_length=200, verbose_name='Account Holder Name')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Opening Balance')),
                ('description', models.TextField(blank=True, verbose_name='Notes/Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Company Account',
                'verbose_name_plural': 'Company Accounts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='My Transport Company', max_length=200)),
                ('address', models.TextField(blank=True, verbose_name='Company Address')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Phone Number')),
                ('gstin', models.CharField(blank=True, max_length=20, verbose_name='GSTIN')),
                ('pan', models.CharField(blank=True, max_length=20, verbose_name='PAN')),
                ('bank_details', models.TextField(blank=True, help_text='Bank Name, Account No, IFSC, etc.', verbose_name='Bank Details')),
                ('authorized_signatory', models.CharField(blank=True, max_length=200, verbose_name='Authorized Signatory Name')),
                ('invoice_template', models.CharField(default='INV-{YYYY}-{SEQ}', help_text='Use {YYYY} for Year, {SEQ} for Sequence Number', max_length=100)),
            ],
            options={
                'verbose_name': 'Company Profile',
                'verbose_name_plural': 'Company Profile',
            },
        ),
        migrations.CreateModel(
            name='FinancialRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Transaction Date')),
                ('record_type', models.CharField(choices=[('Transaction', 'Transaction'), ('Invoice', 'Invoice')], default='Transaction', max_length=20, verbose_name='Record Type')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount')),
                ('entry_number', models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Entry #')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('document_ref', models.FileField(blank=True, null=True, upload_to='financial_docs/%Y/%m/', verbose_name='Supporting Document')),
            ],
            options={
                'verbose_name': 'Financial Record',
                'verbose_name_plural': 'Financial Records',
                'ordering': ['-date'],
                'permissions': [('can_view_financial_records', 'Can view financial records'), ('can_manage_financial_records', 'Can manage financial records')],
            },
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Party Name')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Phone Number')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='State')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('gstin', models.CharField(blank=True, max_length=20, verbose_name='GSTIN')),
                ('bank_name', models.CharField(blank=True, max_length=200, verbose_name='Bank Name')),
                ('account_number', models.CharField(blank=True, max_length=50, verbose_name='Account Number')),
                ('ifsc_code', models.CharField(blank=True, max_length=20, verbose_name='IFSC Code')),
                ('account_holder_name', models.CharField(blank=True, max_length=200, verbose_name='Account Holder Name')),
                ('bank_details', models.TextField(blank=True, verbose_name='Legacy Bank Details (Text)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Party',
                'verbose_name_plural': 'Parties',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(choices=[('Income', 'Income (+)'), ('Expense', 'Expense (-)')], default='Income', max_length=10)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Transaction Category',
                'verbose_name_plural': 'Transaction Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TripAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Allocated Amount')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Trip Allocation',
                'verbose_name_plural': 'Trip Allocations',
            },
        ),
        migrations.CreateModel(
            name='BillTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lr_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='LR No')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_trips', to='ledger.bill')),
            ],
            options={
                'verbose_name': 'Bill Trip',
                'verbose_name_plural': 'Bill Trips',
            },
        ),
    ]
