# Generated by Django 5.1.4 on 2026-01-17 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Transaction Date')),
                ('category', models.CharField(choices=[('Freight Income', 'Freight Income'), ('Fuel Expense', 'Fuel Expense'), ('Maintenance Expense', 'Maintenance Expense'), ('Driver Payment', 'Driver Payment'), ('Other', 'Other')], max_length=30, verbose_name='Category')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount')),
                ('description', models.TextField(verbose_name='Description')),
                ('document_ref', models.FileField(blank=True, null=True, upload_to='financial_docs/%Y/%m/', verbose_name='Supporting Document')),
                ('associated_trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='financial_records', to='trips.trip', verbose_name='Associated Trip')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_financials', to=settings.AUTH_USER_MODEL, verbose_name='Recorded By')),
            ],
            options={
                'verbose_name': 'Financial Record',
                'verbose_name_plural': 'Financial Records',
                'ordering': ['-date'],
                'permissions': [('can_view_financial_records', 'Can view financial records'), ('can_manage_financial_records', 'Can manage financial records')],
            },
        ),
    ]
