# Generated by Django 5.1.4 on 2026-01-17 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0001_initial"),
        ("trips", "0002_remove_trip_client_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="financialrecord",
            name="associated_trip_leg",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="financial_records",
                to="trips.tripleg",
                verbose_name="Associated Trip Leg",
            ),
        ),
    ]
