# Generated by Django 5.1.4 on 2026-03-22 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
        ('ledger', '0001_initial'),
        ('trips', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='billtrip',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_trips', to='trips.trip'),
        ),
        migrations.AddField(
            model_name='bill',
            name='trips',
            field=models.ManyToManyField(related_name='bills', through='ledger.BillTrip', to='trips.trip', verbose_name='Included Trips'),
        ),
        migrations.AddField(
            model_name='bill',
            name='issuer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='ledger.companyaccount', verbose_name='Issued From'),
        ),
        migrations.AddField(
            model_name='financialrecord',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financial_records', to='ledger.companyaccount', verbose_name='Company Account'),
        ),
        migrations.AddField(
            model_name='financialrecord',
            name='associated_bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='financial_records', to='ledger.bill', verbose_name='Associated Bill'),
        ),
        migrations.AddField(
            model_name='financialrecord',
            name='associated_trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='financial_records', to='trips.trip', verbose_name='Associated Trip'),
        ),
        migrations.AddField(
            model_name='financialrecord',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_records', to='drivers.driver', verbose_name='Associated Driver'),
        ),
        migrations.AddField(
            model_name='financialrecord',
            name='recorded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_financials', to=settings.AUTH_USER_MODEL, verbose_name='Recorded By'),
        ),
        migrations.AddField(
            model_name='financialrecord',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_records', to='ledger.party', verbose_name='Associated Party'),
        ),
        migrations.AddField(
            model_name='bill',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='ledger.party', verbose_name='Bill To'),
        ),
        migrations.AddField(
            model_name='financialrecord',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financial_records', to='ledger.transactioncategory', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='tripallocation',
            name='financial_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='ledger.financialrecord', verbose_name='Financial Record'),
        ),
        migrations.AddField(
            model_name='tripallocation',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_allocations', to='trips.trip', verbose_name='Trip'),
        ),
        migrations.AlterUniqueTogether(
            name='billtrip',
            unique_together={('bill', 'trip')},
        ),
        migrations.AlterUniqueTogether(
            name='tripallocation',
            unique_together={('financial_record', 'trip')},
        ),
    ]
