# Generated by Django 5.1.4 on 2026-01-18 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_financialrecord_associated_trip_leg'),
        ('trips', '0004_alter_trip_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Party Name')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Phone Number')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='State')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Party',
                'verbose_name_plural': 'Parties',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='financialrecord',
            name='associated_trip_leg',
        ),
        migrations.AddField(
            model_name='financialrecord',
            name='associated_legs',
            field=models.ManyToManyField(blank=True, related_name='financial_records', to='trips.tripleg', verbose_name='Associated Trip Legs'),
        ),
        migrations.AddField(
            model_name='financialrecord',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_records', to='ledger.party', verbose_name='Associated Party'),
        ),
    ]
