# Generated by Django 5.1.4 on 2026-03-24 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyProfile',
        ),
        migrations.AddField(
            model_name='bill',
            name='invoice_company_authorized_signatory',
            field=models.CharField(blank=True, max_length=200, verbose_name='Authorized Signatory (Snapshot)'),
        ),
        migrations.AddField(
            model_name='companyaccount',
            name='authorized_signatory',
            field=models.CharField(blank=True, max_length=200, verbose_name='Authorized Signatory'),
        ),
        migrations.AddField(
            model_name='companyaccount',
            name='invoice_template',
            field=models.CharField(default='INV/{YYYY}/{SEQ}', help_text='Use {YYYY} for Year, {SEQ} for Sequence Number', max_length=100),
        ),
    ]
