# Generated by Django 5.1.4 on 2026-03-29 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_delete_companyprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='invoice_bank_branch',
            field=models.CharField(blank=True, max_length=200, verbose_name='Bank Branch (Snapshot)'),
        ),
        migrations.AddField(
            model_name='companyaccount',
            name='bank_branch',
            field=models.CharField(blank=True, max_length=200, verbose_name='Bank Branch'),
        ),
        migrations.AddField(
            model_name='party',
            name='bank_branch',
            field=models.CharField(blank=True, max_length=200, verbose_name='Bank Branch'),
        ),
    ]
