# Generated by Django 5.1.4 on 2026-01-18 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0004_financialrecord_driver'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Account Name')),
                ('account_number', models.CharField(blank=True, max_length=50, verbose_name='Account Number')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Opening Balance')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='financialrecord',
            name='category',
            field=models.CharField(choices=[('Freight Income', 'Freight Income (Invoice)'), ('Party Payment', 'Party Payment (Received)'), ('Fuel Expense', 'Fuel Expense'), ('Maintenance Expense', 'Maintenance Expense'), ('Driver Payment', 'Driver Payment'), ('Other', 'Other')], max_length=30, verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='financialrecord',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financial_records', to='ledger.account', verbose_name='Company Account'),
        ),
    ]
