# Generated by Django 5.1.4 on 2026-03-31 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0004_bill_invoice_bank_branch_companyaccount_bank_branch_and_more'),
        ('trips', '0003_trip_diesel_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='amount_override',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Subtotal Amount (Manual)'),
        ),
        migrations.AddField(
            model_name='bill',
            name='bill_type',
            field=models.CharField(choices=[('Trip', 'Trip-based Invoice'), ('Standard', 'Standard Invoice')], default='Trip', max_length=10, verbose_name='Bill Type'),
        ),
        migrations.AddField(
            model_name='bill',
            name='item_type',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Item Type/Description'),
        ),
        migrations.AddField(
            model_name='financialrecord',
            name='is_gst_payment',
            field=models.BooleanField(default=False, help_text='Check if this payment includes GST amount', verbose_name='Is GST Payment?'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='trips',
            field=models.ManyToManyField(blank=True, related_name='bills', through='ledger.BillTrip', to='trips.trip', verbose_name='Included Trips'),
        ),
    ]
