# Generated by Django 5.1.4 on 2026-01-18 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0005_account_alter_financialrecord_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialrecord',
            name='associated_legs',
        ),
    ]
