# Generated by Django 5.1.4 on 2026-03-31 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0005_bill_amount_override_bill_bill_type_bill_item_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialrecord',
            name='is_gst_payment',
        ),
    ]
