# Generated by Django 5.1.4 on 2026-03-31 15:26

import ledger.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0006_remove_financialrecord_is_gst_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialrecord',
            name='document_ref',
            field=models.FileField(blank=True, null=True, upload_to=ledger.models.financial_record_upload_path, verbose_name='Supporting Document'),
        ),
    ]
