# Generated by Django 5.1.4 on 2026-01-18 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0006_remove_financialrecord_associated_legs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialrecord',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
    ]
