# Generated by Django 5.1.4 on 2026-01-18 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0007_alter_financialrecord_description'),
        ('trips', '0007_alter_trip_options_trip_amount_received_trip_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Allocated Amount')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('financial_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='ledger.financialrecord', verbose_name='Financial Record')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_allocations', to='trips.trip', verbose_name='Trip')),
            ],
            options={
                'verbose_name': 'Trip Allocation',
                'verbose_name_plural': 'Trip Allocations',
                'unique_together': {('financial_record', 'trip')},
            },
        ),
    ]
