# Generated by Django 5.1.4 on 2026-03-31 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0007_alter_financialrecord_document_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Opening Balance'),
        ),
    ]
