# Generated by Django 5.1.4 on 2026-03-31 15:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0008_party_opening_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created At'),
            preserve_default=False,
        ),
    ]
