# Generated by Django 5.1.4 on 2026-01-18 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0008_tripallocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialrecord',
            name='entry_number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Entry #'),
        ),
    ]
