# Generated by Django 5.1.4 on 2026-03-31 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0009_financialrecord_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialrecord',
            name='record_type',
            field=models.CharField(choices=[('Transaction', 'Transaction'), ('Invoice', 'Invoice'), ('General', 'General/Miscellaneous')], default='Transaction', max_length=20, verbose_name='Record Type'),
        ),
    ]
