# Generated by Django 5.1.4 on 2026-01-18 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0009_financialrecord_entry_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(choices=[('Income', 'Income (+)'), ('Expense', 'Expense (-)')], default='Income', max_length=10)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Transaction Category',
                'verbose_name_plural': 'Transaction Categories',
                'ordering': ['name'],
            },
        ),
    ]
