# Generated by Django 5.1.4 on 2026-03-31 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0010_alter_financialrecord_record_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyaccount',
            name='invoice_template',
        ),
        migrations.AddField(
            model_name='companyaccount',
            name='invoice_padding',
            field=models.PositiveIntegerField(default=4, help_text='Number of digits for the sequence (e.g. 4 for 0001)'),
        ),
        migrations.AddField(
            model_name='companyaccount',
            name='invoice_prefix',
            field=models.CharField(default='INV/{YYYY}/', help_text='Prefix for invoice numbers. Use {YYYY} for year.', max_length=50),
        ),
        migrations.AddField(
            model_name='companyaccount',
            name='invoice_sequence_start',
            field=models.PositiveIntegerField(default=1, help_text='Start the sequence from this number'),
        ),
        migrations.AddField(
            model_name='companyaccount',
            name='invoice_suffix',
            field=models.CharField(blank=True, help_text='Optional suffix for invoice numbers.', max_length=50),
        ),
    ]
