# Generated by Django 5.1.4 on 2026-01-18 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0010_transactioncategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialrecord',
            name='category_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financial_records', to='ledger.transactioncategory', verbose_name='Category (New)'),
        ),
    ]
