# Generated by Django 5.1.4 on 2026-04-11 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0011_remove_companyaccount_invoice_template_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyaccount',
            options={'ordering': ['-created_at'], 'verbose_name': 'Company Account', 'verbose_name_plural': 'Company Accounts'},
        ),
        migrations.AlterModelOptions(
            name='party',
            options={'ordering': ['-created_at'], 'verbose_name': 'Party', 'verbose_name_plural': 'Parties'},
        ),
        migrations.AlterModelOptions(
            name='transactioncategory',
            options={'ordering': ['-created_at'], 'verbose_name': 'Transaction Category', 'verbose_name_plural': 'Transaction Categories'},
        ),
        migrations.AddField(
            model_name='transactioncategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
