# Generated by Django 5.1.4 on 2026-01-18 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0011_financialrecord_category_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialrecord',
            name='category',
        ),
        migrations.RenameField(
            model_name='financialrecord',
            old_name='category_new',
            new_name='category',
        ),
    ]