# Generated by Django 5.1.4 on 2026-01-18 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0012_remove_financialrecord_category_new_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialrecord',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financial_records', to='ledger.transactioncategory', verbose_name='Category'),
        ),
    ]
