# Generated by Django 6.0.3 on 2026-04-07 09:23

from django.db import migrations

def create_categories(apps, schema_editor):
    TransactionCategory = apps.get_model('ledger', 'TransactionCategory')

    categories = [
        {'name': 'TDS', 'type': 'Expense', 'description': 'Tax Deducted at Source'},
        {'name': 'Shortage', 'type': 'Expense', 'description': 'Deduction for material shortage'},
        {'name': 'Credit Note', 'type': 'Expense', 'description': 'Credit Note (reduces party balance)'},
        {'name': 'Debit Note', 'type': 'Income', 'description': 'Debit Note (increases party balance)'},
    ]

    for cat in categories:
        TransactionCategory.objects.get_or_create(
            name=cat['name'],
            defaults={'type': cat['type'], 'description': cat['description']}
        )

class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0012_default_categories"),
    ]

    operations = [
        migrations.RunPython(create_categories),
    ]
