# Generated by Django 5.1.4 on 2026-04-11 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0012_alter_companyaccount_options_alter_party_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='party_type',
            field=models.CharField(choices=[('Debtor', 'Customer (Debtor)'), ('Creditor', 'Vendor/Supplier (Creditor)')], default='Debtor', max_length=20, verbose_name='Party Type'),
        ),
    ]
