# Generated by Django 5.1.4 on 2026-01-19 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0013_alter_financialrecord_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=100, unique=True)),
                ("value", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
