# Generated by Django 5.1.4 on 2026-04-14 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0013_party_party_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='status',
        ),
    ]
