# Generated by Django 5.1.4 on 2026-04-14 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0014_remove_bill_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='gst_type',
            field=models.CharField(choices=[('GST', 'GST')], default='GST', max_length=10, verbose_name='GST Type'),
        ),
    ]
