# Generated by Django 5.1.4 on 2026-04-14 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0015_alter_bill_gst_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to='ledger.transactioncategory', verbose_name='Bill Category'),
        ),
    ]
