# Generated by Django 5.1.4 on 2026-01-19 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0001_initial"),
        ("ledger", "0015_populate_sequences"),
    ]

    operations = [
        migrations.AddField(
            model_name="financialrecord",
            name="driver_new",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="financial_records_new",
                to="drivers.driver",
                verbose_name="Associated Driver (New)",
            ),
        ),
    ]
