# Generated by Django 5.1.4 on 2026-04-15 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0018_add_payment_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='bill_no',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Invoice No'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Full Invoice Number'),
        ),
    ]
