# Generated by Django 5.1.4 on 2026-01-24 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0019_alter_financialrecord_driver"),
    ]

    operations = [
        migrations.AddField(
            model_name="financialrecord",
            name="record_type",
            field=models.CharField(
                choices=[("Transaction", "Transaction"), ("Invoice", "Invoice")],
                default="Transaction",
                max_length=20,
                verbose_name="Record Type",
            ),
        ),
    ]
