# Generated by Django 5.1.4 on 2026-04-21 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0019_bill_bill_no_alter_bill_bill_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='gst_type',
            field=models.CharField(choices=[('GST', 'GST'), ('IGST', 'IGST')], default='GST', max_length=10, verbose_name='GST Type'),
        ),
    ]
