# Generated by Django 5.1.4 on 2026-01-29 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0020_financialrecord_record_type"),
        ("trips", "0016_alter_trip_delivery_lat_alter_trip_delivery_lng_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(default="My Transport Company", max_length=200),
                ),
                (
                    "address",
                    models.TextField(blank=True, verbose_name="Company Address"),
                ),
                (
                    "bank_details",
                    models.TextField(
                        blank=True,
                        help_text="Bank Name, Account No, IFSC, etc.",
                        verbose_name="Bank Details",
                    ),
                ),
                (
                    "authorized_signatory",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Authorized Signatory Name",
                    ),
                ),
                (
                    "invoice_template",
                    models.CharField(
                        default="INV-{YYYY}-{SEQ}",
                        help_text="Use {YYYY} for Year, {SEQ} for Sequence Number",
                        max_length=100,
                    ),
                ),
            ],
            options={
                "verbose_name": "Company Profile",
                "verbose_name_plural": "Company Profile",
            },
        ),
        migrations.CreateModel(
            name="Bill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bill_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        unique=True,
                        verbose_name="Invoice Number",
                    ),
                ),
                ("date", models.DateField(verbose_name="Invoice Date")),
                (
                    "gst_rate",
                    models.PositiveIntegerField(
                        choices=[(0, "0% GST"), (5, "5% GST"), (18, "18% GST")],
                        default=0,
                        verbose_name="GST Rate (%)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Draft", "Draft"), ("Final", "Final")],
                        default="Draft",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bills",
                        to="ledger.party",
                        verbose_name="Bill To",
                    ),
                ),
                (
                    "trips",
                    models.ManyToManyField(
                        related_name="bills",
                        to="trips.trip",
                        verbose_name="Included Trips",
                    ),
                ),
            ],
        ),
    ]
