# Generated by Django 5.1.4 on 2026-04-21 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0020_alter_bill_gst_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='original_bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustment_bills', to='ledger.bill', verbose_name='Against Invoice'),
        ),
    ]
