# Generated by Django 5.1.4 on 2026-04-21 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0021_bill_original_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='standard_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Standard Rate'),
        ),
        migrations.AddField(
            model_name='bill',
            name='standard_weight',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Standard Weight'),
        ),
    ]
