# Generated by Django 5.1.4 on 2026-01-29 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0021_companyprofile_bill"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bill",
            name="bill_number",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                unique=True,
                verbose_name="Invoice Number",
            ),
        ),
    ]
