# Generated by Django 5.1.4 on 2026-02-01 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0022_alter_bill_bill_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="bill",
            name="gst_type",
            field=models.CharField(
                choices=[
                    ("INTRA", "Intra-state (CGST + SGST)"),
                    ("INTER", "Inter-state (IGST)"),
                ],
                default="INTRA",
                max_length=10,
                verbose_name="GST Type",
            ),
        ),
        migrations.AddField(
            model_name="bill",
            name="invoice_company_address",
            field=models.TextField(
                blank=True, verbose_name="Company Address (Snapshot)"
            ),
        ),
        migrations.AddField(
            model_name="bill",
            name="invoice_company_gstin",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Company GSTIN (Snapshot)"
            ),
        ),
        migrations.AddField(
            model_name="bill",
            name="invoice_company_mobile",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Company Mobile (Snapshot)"
            ),
        ),
        migrations.AddField(
            model_name="bill",
            name="invoice_company_name",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Company Name (Snapshot)"
            ),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="gstin",
            field=models.CharField(blank=True, max_length=20, verbose_name="GSTIN"),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Phone Number"
            ),
        ),
        migrations.AddField(
            model_name="party",
            name="bank_details",
            field=models.TextField(blank=True, verbose_name="Bank Details"),
        ),
        migrations.AddField(
            model_name="party",
            name="gstin",
            field=models.CharField(blank=True, max_length=20, verbose_name="GSTIN"),
        ),
    ]
