# Generated by Django 5.1.4 on 2026-04-21 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0022_bill_standard_rate_bill_standard_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='use_roundoff',
            field=models.BooleanField(default=True, verbose_name='Use Round Off'),
        ),
    ]
