# Generated by Django 5.1.4 on 2026-02-22 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0023_bill_gst_type_bill_invoice_company_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='gst_type',
            field=models.CharField(choices=[('INTRA', 'Intra-state'), ('INTER', 'Inter-state')], default='INTRA', max_length=10, verbose_name='GST Type'),
        ),
    ]
