# Generated by Django 5.1.4 on 2026-04-28 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0023_bill_use_roundoff'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyaccount',
            name='cn_prefix',
            field=models.CharField(default='CN-{YYYY}/', help_text='Prefix for Credit Notes. Use {YYYY} for year.', max_length=50),
        ),
        migrations.AddField(
            model_name='companyaccount',
            name='dn_prefix',
            field=models.CharField(default='DN-{YYYY}/', help_text='Prefix for Debit Notes. Use {YYYY} for year.', max_length=50),
        ),
    ]
