# Generated by Django 5.1.4 on 2026-04-29 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0024_companyaccount_cn_prefix_companyaccount_dn_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyaccount',
            name='current_balance_cached',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Current Balance'),
        ),
        migrations.AddField(
            model_name='party',
            name='current_balance_cached',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Current Balance'),
        ),
        migrations.AddField(
            model_name='party',
            name='total_credit_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Received/Credit'),
        ),
        migrations.AddField(
            model_name='party',
            name='total_debit_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Billed/Debit'),
        ),
    ]
