# Generated by Django 5.1.4 on 2026-02-22 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0024_alter_bill_gst_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='description',
            field=models.TextField(blank=True, help_text='Description shown on invoice (e.g., destination/material)', verbose_name='Item Description'),
        ),
        migrations.AddField(
            model_name='bill',
            name='hsn_code',
            field=models.CharField(default='996511', max_length=20, verbose_name='HSN Code'),
        ),
        migrations.AddField(
            model_name='bill',
            name='reverse_charge',
            field=models.BooleanField(default=False, verbose_name='Reverse Charge'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='pan',
            field=models.CharField(blank=True, max_length=20, verbose_name='PAN'),
        ),
    ]
