# Generated by Django 5.1.4 on 2026-02-22 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0025_bill_description_bill_hsn_code_bill_reverse_charge_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="financialrecord",
            name="associated_bill",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="financial_records",
                to="ledger.bill",
                verbose_name="Associated Bill",
            ),
        ),
    ]
