# Generated by Django 5.1.4 on 2026-04-29 15:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0005_drivertransaction_drivers_dri_date_f5cc84_idx_and_more'),
        ('ledger', '0025_companyaccount_current_balance_cached_and_more'),
        ('trips', '0009_trip_lr_no'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='financialrecord',
            index=models.Index(fields=['date', 'created_at'], name='ledger_fina_date_ea6e31_idx'),
        ),
        migrations.AddIndex(
            model_name='financialrecord',
            index=models.Index(fields=['account', 'date'], name='ledger_fina_account_3e3372_idx'),
        ),
        migrations.AddIndex(
            model_name='financialrecord',
            index=models.Index(fields=['party', 'date'], name='ledger_fina_party_i_34e70b_idx'),
        ),
        migrations.AddIndex(
            model_name='financialrecord',
            index=models.Index(fields=['driver', 'date'], name='ledger_fina_driver__56f652_idx'),
        ),
        migrations.AddIndex(
            model_name='financialrecord',
            index=models.Index(fields=['record_type', 'date'], name='ledger_fina_record__4e4c52_idx'),
        ),
    ]
