# Generated by Django 5.1.4 on 2026-03-03 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0026_financialrecord_associated_bill'),
        ('trips', '0016_alter_trip_delivery_lat_alter_trip_delivery_lng_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='trips',
        ),
        migrations.CreateModel(
            name='BillTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lr_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='LR No')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_trips', to='ledger.bill')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_trips', to='trips.trip')),
            ],
            options={
                'verbose_name': 'Bill Trip',
                'verbose_name_plural': 'Bill Trips',
                'unique_together': {('bill', 'trip')},
            },
        ),
        migrations.AddField(
            model_name='bill',
            name='trips',
            field=models.ManyToManyField(related_name='bills', through='ledger.BillTrip', to='trips.trip', verbose_name='Included Trips'),
        ),
    ]
