# Generated by Django 5.1.4 on 2026-05-01 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0013_add_deduction_categories'),
        ('ledger', '0026_financialrecord_ledger_fina_date_ea6e31_idx_and_more'),
    ]

    operations = [
    ]
