# Generated by Django 5.1.4 on 2026-05-03 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0027_merge_20260501_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='gst_type',
            field=models.CharField(choices=[('GST', 'GST'), ('IGST', 'IGST'), ('NONE', 'Non-GST')], default='GST', max_length=10, verbose_name='GST Type'),
        ),
    ]
