# Generated by Django 5.1.4 on 2026-03-03 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0027_billtrip_alter_bill_trips'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Firm Name')),
                ('address', models.TextField(blank=True, verbose_name='Firm Address')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Phone Number')),
                ('gstin', models.CharField(blank=True, max_length=20, verbose_name='GSTIN')),
                ('pan', models.CharField(blank=True, max_length=20, verbose_name='PAN')),
                ('bank_name', models.CharField(blank=True, max_length=200, verbose_name='Bank Name')),
                ('account_number', models.CharField(blank=True, max_length=50, verbose_name='Account Number')),
                ('ifsc_code', models.CharField(blank=True, max_length=20, verbose_name='IFSC Code')),
                ('account_holder_name', models.CharField(blank=True, max_length=200, verbose_name='Account Holder Name')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Opening Balance')),
                ('description', models.TextField(blank=True, verbose_name='Notes/Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Company Account',
                'verbose_name_plural': 'Company Accounts',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='bill',
            name='invoice_bank_account',
            field=models.CharField(blank=True, max_length=50, verbose_name='Bank Account (Snapshot)'),
        ),
        migrations.AddField(
            model_name='bill',
            name='invoice_bank_ifsc',
            field=models.CharField(blank=True, max_length=20, verbose_name='Bank IFSC (Snapshot)'),
        ),
        migrations.AddField(
            model_name='bill',
            name='invoice_bank_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Bank Name (Snapshot)'),
        ),
        migrations.AddField(
            model_name='party',
            name='account_holder_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Account Holder Name'),
        ),
        migrations.AddField(
            model_name='party',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Account Number'),
        ),
        migrations.AddField(
            model_name='party',
            name='bank_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Bank Name'),
        ),
        migrations.AddField(
            model_name='party',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='IFSC Code'),
        ),
        migrations.AlterField(
            model_name='party',
            name='bank_details',
            field=models.TextField(blank=True, verbose_name='Legacy Bank Details (Text)'),
        ),
        migrations.AddField(
            model_name='bill',
            name='issuer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='ledger.companyaccount', verbose_name='Issued From'),
        ),
        migrations.AlterField(
            model_name='financialrecord',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financial_records', to='ledger.companyaccount', verbose_name='Company Account'),
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
