# Generated by Django 5.1.4 on 2026-05-07 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0028_alter_bill_gst_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialrecord',
            name='tds_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='TDS %'),
        ),
    ]
