# Generated by Django 5.1.4 on 2026-05-07 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0029_financialrecord_tds_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Discount'),
        ),
        migrations.AddField(
            model_name='billtrip',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Discount'),
        ),
    ]
