# Generated by Django 5.1.4 on 2026-05-08 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0030_bill_discount_billtrip_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='manual_original_bill_date',
            field=models.DateField(blank=True, null=True, verbose_name='Manual Against Invoice Date'),
        ),
        migrations.AddField(
            model_name='bill',
            name='manual_original_bill_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Manual Against Invoice No'),
        ),
    ]
