# Generated by Django 5.1.4 on 2026-05-10 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0031_bill_manual_original_bill_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='description',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='hsn_code',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='reverse_charge',
        ),
        migrations.AddField(
            model_name='bill',
            name='amount_received_cached',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Amount Received (Cached)'),
        ),
        migrations.AddField(
            model_name='bill',
            name='gst_amount_cached',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='GST (Cached)'),
        ),
        migrations.AddField(
            model_name='bill',
            name='outstanding_balance_cached',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Outstanding (Cached)'),
        ),
        migrations.AddField(
            model_name='bill',
            name='payment_status_cached',
            field=models.CharField(default='Unpaid', max_length=20, verbose_name='Payment Status (Cached)'),
        ),
        migrations.AddField(
            model_name='bill',
            name='subtotal_cached',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Subtotal (Cached)'),
        ),
        migrations.AddField(
            model_name='bill',
            name='total_amount_cached',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Amount (Cached)'),
        ),
    ]
