# Generated by Django 5.1.4 on 2026-05-10 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0032_remove_bill_description_remove_bill_hsn_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='description',
            field=models.TextField(blank=True, help_text='Description shown on invoice (e.g., destination/material)', verbose_name='Item Description'),
        ),
        migrations.AddField(
            model_name='bill',
            name='hsn_code',
            field=models.CharField(default='996511', max_length=20, verbose_name='HSN Code'),
        ),
        migrations.AddField(
            model_name='bill',
            name='reverse_charge',
            field=models.BooleanField(default=False, verbose_name='Reverse Charge'),
        ),
    ]
