# Generated by Django 5.1.4 on 2026-05-14 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0033_bill_description_bill_hsn_code_bill_reverse_charge'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Allocated Amount')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_allocations', to='ledger.bill', verbose_name='Bill')),
                ('financial_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_allocations', to='ledger.financialrecord', verbose_name='Financial Record')),
            ],
            options={
                'verbose_name': 'Bill Allocation',
                'verbose_name_plural': 'Bill Allocations',
                'unique_together': {('financial_record', 'bill')},
            },
        ),
    ]
