# Generated by Django 6.0.7 on 2026-07-16 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0035_bill_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='date',
            field=models.DateField(db_index=True, verbose_name='Invoice Date'),
        ),
    ]
