# Generated by Django 6.0.7 on 2026-07-30 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0017_tyre_vendor'),
        ('ledger', '0036_alter_bill_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialrecord',
            name='associated_tyre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='financial_records', to='fleet.tyre', verbose_name='Associated Tyre'),
        ),
    ]
