# Generated by Django 6.1.1 on 2026-10-02 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0019_alter_tyre_photo'),
        ('ledger', '0037_financialrecord_associated_tyre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialrecord',
            name='associated_tyre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_records', to='fleet.tyre', verbose_name='Associated Tyre'),
        ),
    ]
