# Generated by Django 6.1.1 on 2026-10-04 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0038_alter_financialrecord_associated_tyre'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='creditor_invoice_date',
            field=models.DateField(blank=True, null=True, verbose_name='Creditor Invoice Date'),
        ),
        migrations.AddField(
            model_name='bill',
            name='creditor_invoice_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Creditor Invoice Number'),
        ),
        migrations.AddField(
            model_name='bill',
            name='customer_bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creditor_bills', to='ledger.bill', verbose_name='Customer Bill Reference'),
        ),
    ]
