# Generated by Django 6.1.1 on 2026-10-10 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0014_populate_pucc_base_document'),
        ('ledger', '0039_bill_creditor_invoice_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialrecord',
            name='associated_document_renewal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='financial_records', to='documents.documentrenewal', verbose_name='Associated Document Renewal'),
        ),
    ]
