# Generated by Django 5.1.4 on 2026-01-17 13:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Driver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employee_id",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Employee ID"
                    ),
                ),
                (
                    "license_number",
                    models.CharField(max_length=50, verbose_name="License Number"),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=20, verbose_name="Phone Number"),
                ),
                ("address", models.TextField(blank=True, verbose_name="Address")),
                (
                    "joined_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Joined Date"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="driver_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User Account",
                    ),
                ),
            ],
            options={
                "verbose_name": "Driver",
                "verbose_name_plural": "Drivers",
                "permissions": [
                    ("can_view_all_drivers", "Can view all drivers"),
                    ("can_manage_driver_finance", "Can manage driver finances"),
                ],
            },
        ),
        migrations.CreateModel(
            name="DriverTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Transaction Date",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("Salary", "Salary Credit (+)"),
                            ("Allowance", "Allowance Credit (+)"),
                            ("Loan", "Loan (Debit -)"),
                            ("Payment", "Payment (Debit -)"),
                            ("Repayment", "Repayment (Credit +)"),
                            ("Other", "Other"),
                        ],
                        max_length=30,
                        verbose_name="Type",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Positive: Company owes Driver. Negative: Driver owes Company.",
                        max_digits=12,
                        verbose_name="Amount",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_driver_transactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="drivers.driver",
                        verbose_name="Driver",
                    ),
                ),
            ],
            options={
                "verbose_name": "Driver Transaction",
                "verbose_name_plural": "Driver Transactions",
                "ordering": ["-date", "-created_at"],
            },
        ),
    ]
