# Generated by Django 5.1.4 on 2026-04-11 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_alter_driver_employee_id_alter_driver_license_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driver',
            options={'ordering': ['-joined_date', '-id'], 'permissions': [('can_view_all_drivers', 'Can view all drivers'), ('can_manage_driver_finance', 'Can manage driver finances')], 'verbose_name': 'Driver', 'verbose_name_plural': 'Drivers'},
        ),
    ]
