# Generated by Django 5.1.4 on 2026-04-29 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_alter_driver_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='current_balance_cached',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Current Balance'),
        ),
    ]
