# Generated by Django 5.1.4 on 2026-04-29 15:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0004_driver_current_balance_cached'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='drivertransaction',
            index=models.Index(fields=['date', 'created_at'], name='drivers_dri_date_f5cc84_idx'),
        ),
        migrations.AddIndex(
            model_name='drivertransaction',
            index=models.Index(fields=['driver', 'date'], name='drivers_dri_driver__390662_idx'),
        ),
        migrations.AddIndex(
            model_name='drivertransaction',
            index=models.Index(fields=['transaction_type'], name='drivers_dri_transac_25c160_idx'),
        ),
    ]
