# Generated by Django 5.1.4 on 2026-01-17 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_plate', models.CharField(max_length=20, unique=True, verbose_name='Registration Plate')),
                ('make_model', models.CharField(max_length=200, verbose_name='Make & Model')),
                ('purchase_date', models.DateField(verbose_name='Purchase Date')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Maintenance', 'Maintenance'), ('Retired', 'Retired')], default='Active', max_length=20, verbose_name='Vehicle Status')),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
                'ordering': ['registration_plate'],
                'permissions': [('can_view_all_vehicles', 'Can view all vehicles')],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Maintenance Date')),
                ('type', models.CharField(choices=[('Routine Service', 'Routine Service'), ('Repair', 'Repair')], max_length=20, verbose_name='Maintenance Type')),
                ('description', models.TextField(verbose_name='Description of Work')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cost')),
                ('service_provider', models.CharField(max_length=200, verbose_name='Service Provider')),
                ('next_service_due', models.DateField(blank=True, null=True, verbose_name='Next Service Due')),
                ('logged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logged_maintenance', to=settings.AUTH_USER_MODEL, verbose_name='Logged By')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='fleet.vehicle', verbose_name='Vehicle')),
            ],
            options={
                'verbose_name': 'Maintenance Log',
                'verbose_name_plural': 'Maintenance Logs',
                'ordering': ['-date'],
                'permissions': [('can_create_maintenance_log', 'Can create maintenance log')],
            },
        ),
    ]
