# Generated by Django 5.1.4 on 2026-03-22 11:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('liters', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Liters')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Rate per Liter')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total Cost')),
                ('odometer', models.PositiveIntegerField(verbose_name='Odometer Reading')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fuel Log',
                'verbose_name_plural': 'Fuel Logs',
                'ordering': ['-date', '-odometer'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Maintenance Date')),
                ('type', models.CharField(choices=[('Routine Service', 'Routine Service'), ('Oil Change', 'Oil Change'), ('Tyre Work', 'Tyre Work'), ('Major Service', 'Major Service'), ('Repair', 'Repair')], default='Routine Service', max_length=50, verbose_name='Maintenance Type')),
                ('odometer_reading', models.PositiveIntegerField(blank=True, null=True, verbose_name='Odometer Reading')),
                ('description', models.TextField(verbose_name='Description of Work')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cost')),
                ('service_provider', models.CharField(max_length=200, verbose_name='Service Provider')),
                ('next_service_due', models.DateField(blank=True, null=True, verbose_name='Next Service Due (Date)')),
                ('next_service_odometer', models.PositiveIntegerField(blank=True, null=True, verbose_name='Next Service Due (Odometer)')),
            ],
            options={
                'verbose_name': 'Maintenance Log',
                'verbose_name_plural': 'Maintenance Logs',
                'ordering': ['-date'],
                'permissions': [('can_create_maintenance_log', 'Can create maintenance log')],
            },
        ),
        migrations.CreateModel(
            name='Tyre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True, verbose_name='Serial Number')),
                ('brand', models.CharField(max_length=100, verbose_name='Brand')),
                ('size', models.CharField(max_length=50, verbose_name='Size')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='Purchase Date')),
                ('purchase_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('current_position', models.CharField(blank=True, max_length=50, verbose_name='Position')),
                ('status', models.CharField(choices=[('In Stock', 'In Stock'), ('Mounted', 'Mounted'), ('Under Repair', 'Under Repair'), ('Scrap', 'Scrap')], default='In Stock', max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TyreLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('action', models.CharField(choices=[('Mount', 'Mount'), ('Dismount', 'Dismount'), ('Rotation', 'Rotation'), ('Repair', 'Repair'), ('Scrap', 'Scrap')], max_length=20)),
                ('position', models.CharField(blank=True, max_length=50)),
                ('odometer', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_plate', models.CharField(max_length=20, unique=True, verbose_name='Registration Plate')),
                ('make_model', models.CharField(max_length=200, verbose_name='Make & Model')),
                ('purchase_date', models.DateField(verbose_name='Purchase Date')),
                ('current_odometer', models.PositiveIntegerField(default=0, verbose_name='Current Odometer (km)')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Maintenance', 'Maintenance'), ('Retired', 'Retired')], default='Active', max_length=20, verbose_name='Vehicle Status')),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
                'ordering': ['registration_plate'],
                'permissions': [('can_view_all_vehicles', 'Can view all vehicles')],
            },
        ),
    ]
