# Generated by Django 5.1.4 on 2026-03-22 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0001_initial'),
        ('trips', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fuellog',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel_logs', to='trips.trip', verbose_name='Related Trip'),
        ),
        migrations.AddField(
            model_name='maintenancelog',
            name='logged_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logged_maintenance', to=settings.AUTH_USER_MODEL, verbose_name='Logged By'),
        ),
        migrations.AddField(
            model_name='tyrelog',
            name='tyre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='fleet.tyre'),
        ),
        migrations.AddField(
            model_name='tyrelog',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet.vehicle'),
        ),
        migrations.AddField(
            model_name='tyre',
            name='current_vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tyres', to='fleet.vehicle', verbose_name='Current Vehicle'),
        ),
        migrations.AddField(
            model_name='maintenancelog',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='fleet.vehicle', verbose_name='Vehicle'),
        ),
        migrations.AddField(
            model_name='fuellog',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_logs', to='fleet.vehicle', verbose_name='Vehicle'),
        ),
    ]
