# Generated by Django 5.1.4 on 2026-01-19 13:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleet", "0001_initial"),
        ("trips", "0014_trip_end_odometer_trip_start_odometer"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="current_odometer",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Current Odometer (km)"
            ),
        ),
        migrations.CreateModel(
            name="FuelLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Date"
                    ),
                ),
                (
                    "liters",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Liters"
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Rate per Liter"
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Total Cost"
                    ),
                ),
                (
                    "odometer",
                    models.PositiveIntegerField(verbose_name="Odometer Reading"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "trip",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fuel_logs",
                        to="trips.trip",
                        verbose_name="Related Trip",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fuel_logs",
                        to="fleet.vehicle",
                        verbose_name="Vehicle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fuel Log",
                "verbose_name_plural": "Fuel Logs",
                "ordering": ["-date", "-odometer"],
            },
        ),
    ]
