# Generated by Django 5.1.4 on 2026-01-19 17:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_vehicle_current_odometer_fuellog'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancelog',
            name='next_service_odometer',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Next Service Due (Odometer)'),
        ),
        migrations.AddField(
            model_name='maintenancelog',
            name='odometer_reading',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Odometer Reading'),
        ),
        migrations.AlterField(
            model_name='maintenancelog',
            name='next_service_due',
            field=models.DateField(blank=True, null=True, verbose_name='Next Service Due (Date)'),
        ),
        migrations.AlterField(
            model_name='maintenancelog',
            name='type',
            field=models.CharField(choices=[('Routine Service', 'Routine Service'), ('Oil Change', 'Oil Change'), ('Tyre Work', 'Tyre Work'), ('Major Service', 'Major Service'), ('Repair', 'Repair')], default='Routine Service', max_length=50, verbose_name='Maintenance Type'),
        ),
        migrations.CreateModel(
            name='Tyre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True, verbose_name='Serial Number')),
                ('brand', models.CharField(max_length=100, verbose_name='Brand')),
                ('size', models.CharField(max_length=50, verbose_name='Size')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='Purchase Date')),
                ('purchase_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('current_position', models.CharField(blank=True, max_length=50, verbose_name='Position')),
                ('status', models.CharField(choices=[('In Stock', 'In Stock'), ('Mounted', 'Mounted'), ('Under Repair', 'Under Repair'), ('Scrap', 'Scrap')], default='In Stock', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('current_vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tyres', to='fleet.vehicle', verbose_name='Current Vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='TyreLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('action', models.CharField(choices=[('Mount', 'Mount'), ('Dismount', 'Dismount'), ('Rotation', 'Rotation'), ('Repair', 'Repair'), ('Scrap', 'Scrap')], max_length=20)),
                ('position', models.CharField(blank=True, max_length=50)),
                ('odometer', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('tyre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='fleet.tyre')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet.vehicle')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
