# Generated by Django 5.1.4 on 2026-03-26 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tyre',
            name='total_km',
            field=models.PositiveIntegerField(default=0, verbose_name='Total KM'),
        ),
    ]
