# Generated by Django 5.1.4 on 2026-03-26 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_tyre_total_km'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tyrelog',
            name='odometer',
        ),
        migrations.AddField(
            model_name='tyrelog',
            name='distance_covered',
            field=models.PositiveIntegerField(default=0, verbose_name='Distance Covered on Vehicle'),
        ),
        migrations.AddField(
            model_name='tyrelog',
            name='tyre_odo',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Tyre Odo (Total KM)'),
        ),
    ]
