# Generated by Django 5.1.4 on 2026-03-29 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0004_remove_tyrelog_odometer_tyrelog_distance_covered_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancelog',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cost'),
        ),
        migrations.AlterField(
            model_name='maintenancelog',
            name='service_provider',
            field=models.CharField(blank=True, max_length=200, verbose_name='Service Provider'),
        ),
        migrations.AlterField(
            model_name='maintenancelog',
            name='type',
            field=models.CharField(choices=[('Routine Service', 'Routine Service'), ('Oil Change', 'Oil Change'), ('Tyre Work', 'Tyre Work'), ('Major Service', 'Major Service'), ('Repair', 'Repair'), ('Check', 'Check')], default='Routine Service', max_length=50, verbose_name='Maintenance Type'),
        ),
        migrations.CreateModel(
            name='MaintenanceTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Oil Change, Coolant Check, Battery Inspection', max_length=100, verbose_name='Task Name')),
                ('interval_km', models.PositiveIntegerField(blank=True, help_text='Leave blank if not distance-based.', null=True, verbose_name='Interval (km)')),
                ('interval_days', models.PositiveIntegerField(blank=True, help_text='Leave blank if not time-based.', null=True, verbose_name='Interval (days)')),
                ('last_performed_km', models.PositiveIntegerField(default=0, verbose_name='Last Performed Odometer (km)')),
                ('last_performed_date', models.DateField(blank=True, null=True, verbose_name='Last Performed Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_tasks', to='fleet.vehicle', verbose_name='Vehicle')),
            ],
            options={
                'verbose_name': 'Maintenance Task',
                'verbose_name_plural': 'Maintenance Tasks',
                'unique_together': {('vehicle', 'name')},
            },
        ),
        migrations.AddField(
            model_name='maintenancelog',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='fleet.maintenancetask', verbose_name='Maintenance Task'),
        ),
    ]
