# Generated by Django 5.1.4 on 2026-04-05 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0005_alter_maintenancelog_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tyre',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='tyres/', verbose_name='Tyre Photo'),
        ),
        migrations.AlterField(
            model_name='tyrelog',
            name='action',
            field=models.CharField(choices=[('Mount', 'Mount'), ('Dismount', 'Dismount'), ('Rotation', 'Rotation'), ('Repair', 'Repair'), ('Remold', 'Remold'), ('Scrap', 'Scrap')], max_length=20),
        ),
    ]
