# Generated by Django 5.1.4 on 2026-04-11 08:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0006_tyre_photo_alter_tyrelog_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='maintenancetask',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='maintenancetask',
            name='vehicle',
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Oil Change, Brake Inspection', max_length=100, verbose_name='Maintenance Task Name')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Is Completed?')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Next Due Date')),
                ('expiry_km', models.PositiveIntegerField(blank=True, null=True, verbose_name='Next Due Odometer (km)')),
                ('interval_days', models.PositiveIntegerField(blank=True, help_text='Leave blank if not recurring by time.', null=True, verbose_name='Interval (days)')),
                ('interval_km', models.PositiveIntegerField(blank=True, help_text='Leave blank if not recurring by distance.', null=True, verbose_name='Interval (km)')),
                ('completion_date', models.DateField(blank=True, null=True, verbose_name='Date Completed')),
                ('completion_km', models.PositiveIntegerField(blank=True, null=True, verbose_name='Odometer when Completed')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cost')),
                ('service_provider', models.CharField(blank=True, max_length=200, verbose_name='Service Provider')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('logged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logged_maintenance_records', to=settings.AUTH_USER_MODEL, verbose_name='Logged By')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='fleet.vehicle', verbose_name='Vehicle')),
            ],
            options={
                'verbose_name': 'Maintenance Record',
                'verbose_name_plural': 'Maintenance Records',
                'ordering': ['is_completed', 'expiry_date', '-completion_date'],
            },
        ),
        migrations.DeleteModel(
            name='MaintenanceLog',
        ),
        migrations.DeleteModel(
            name='MaintenanceTask',
        ),
    ]
