# Generated by Django 5.1.4 on 2026-04-11 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0007_alter_maintenancetask_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FuelLog',
        ),
    ]
