# Generated by Django 5.1.4 on 2026-04-11 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0008_delete_fuellog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tyre',
            name='total_km',
        ),
        migrations.RemoveField(
            model_name='tyrelog',
            name='distance_covered',
        ),
        migrations.RemoveField(
            model_name='tyrelog',
            name='tyre_odo',
        ),
    ]
