# Generated by Django 5.1.4 on 2026-04-11 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0009_remove_tyre_total_km_remove_tyrelog_distance_covered_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenancerecord',
            options={'ordering': ['is_completed', 'expiry_date', '-completion_date', '-created_at'], 'verbose_name': 'Maintenance Record', 'verbose_name_plural': 'Maintenance Records'},
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ['-registration_plate'], 'verbose_name': 'Vehicle', 'verbose_name_plural': 'Vehicles'},
        ),
    ]
