# Generated by Django 5.1.4 on 2026-05-17 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0010_alter_maintenancerecord_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tyrelog',
            options={'ordering': ['-date', '-created_at', '-id']},
        ),
        migrations.AddField(
            model_name='tyrelog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tyrelog',
            name='logged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logged_tyre_actions', to=settings.AUTH_USER_MODEL, verbose_name='Logged By'),
        ),
    ]
