# Generated by Django 5.1.4 on 2026-05-17 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0011_alter_tyrelog_options_tyrelog_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tyrelog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
