# Generated by Django 6.0.7 on 2026-07-18 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0012_alter_tyrelog_created_at'),
        ('ledger', '0036_alter_bill_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='ownership',
            field=models.CharField(choices=[('Owned', 'Owned (Company Fleet)'), ('Attached', 'Attached (Market Vehicle)')], default='Owned', max_length=20, verbose_name='Ownership Type'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vendor',
            field=models.ForeignKey(blank=True, help_text='Required if Ownership Type is Attached', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attached_vehicles', to='ledger.party', verbose_name='Vendor / Owner'),
        ),
    ]
