# Generated by Django 6.0.7 on 2026-07-30 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0013_vehicle_ownership_vehicle_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tyre',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Size'),
        ),
        migrations.AlterField(
            model_name='tyrelog',
            name='action',
            field=models.CharField(choices=[('Mount', 'Mount'), ('Dismount', 'Dismount'), ('Rotation', 'Rotation'), ('Repair', 'Repair'), ('Remold', 'Remold'), ('Scrap', 'Scrap'), ('Stock', 'Stock')], max_length=20),
        ),
    ]
