# Generated by Django 6.0.7 on 2026-07-30 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0014_alter_tyre_size_alter_tyrelog_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='TyreBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Brand / Make')),
                ('suggestive_price', models.DecimalField(decimal_places=2, default=0, help_text='Suggested purchase price for tyres of this brand', max_digits=10, verbose_name='Suggestive Price')),
            ],
            options={
                'verbose_name': 'Tyre Brand',
                'verbose_name_plural': 'Tyre Brands',
                'ordering': ['name'],
            },
        ),
    ]
