# Generated by Django 6.0.7 on 2026-07-30 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0015_tyrebrand'),
        ('ledger', '0036_alter_bill_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tyrebrand',
            name='vendor',
            field=models.ForeignKey(blank=True, help_text='Vendor to automatically bill when a tyre of this brand is created', limit_choices_to={'party_type': 'Creditor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ledger.party', verbose_name='Default Vendor'),
        ),
    ]
