# Generated by Django 6.0.7 on 2026-07-30 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0016_tyrebrand_vendor'),
        ('ledger', '0036_alter_bill_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tyre',
            name='vendor',
            field=models.ForeignKey(blank=True, limit_choices_to={'party_type': 'Creditor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ledger.party', verbose_name='Vendor'),
        ),
    ]
