# Generated by Django 6.0.7 on 2026-09-16 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0017_tyre_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='chassis_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Chassis Number'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='engine_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Engine Number'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='purchase_date',
            field=models.DateField(blank=True, null=True, verbose_name='Purchase Date'),
        ),
    ]
