# Generated by Django 6.1.1 on 2026-10-02 16:15

import fleet.models.tyre
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0018_vehicle_chassis_number_vehicle_engine_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tyre',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=fleet.models.tyre.tyre_photo_upload_path, verbose_name='Tyre Photo'),
        ),
    ]
