# Generated by Django 6.1.1 on 2026-10-10 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0020_vehicle_created_at_vehicle_created_by_and_more'),
        ('ledger', '0039_bill_creditor_invoice_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='company_account',
            field=models.ForeignKey(blank=True, help_text='Company account / firm that owns this vehicle', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='ledger.companyaccount', verbose_name='Company Account'),
        ),
    ]
