# Generated by Django 5.1.4 on 2026-01-19 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("drivers", "0001_initial"),
        ("fleet", "0002_vehicle_current_odometer_fuellog"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(max_length=100, verbose_name="Document Type"),
                ),
                (
                    "document_number",
                    models.CharField(max_length=100, verbose_name="Document Number"),
                ),
                ("expiry_date", models.DateField(verbose_name="Expiry Date")),
                (
                    "scanned_copy",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="documents/%Y/%m/",
                        verbose_name="Scanned Copy",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="drivers.driver",
                        verbose_name="Driver",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="fleet.vehicle",
                        verbose_name="Vehicle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
                "ordering": ["expiry_date"],
            },
        ),
    ]
