# Generated by Django 5.1.4 on 2026-03-31 11:48

import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_document_never_expires_document_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='scanned_copy',
            field=models.FileField(blank=True, null=True, upload_to=documents.models.document_upload_path, verbose_name='Scanned Copy'),
        ),
    ]
