# Generated by Django 5.1.4 on 2026-04-11 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_document_scanned_copy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['expiry_date', '-created_at'], 'verbose_name': 'Document', 'verbose_name_plural': 'Documents'},
        ),
    ]
