# Generated by Django 5.1.4 on 2026-05-28 16:40

import django.db.models.deletion
import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_document_added_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='document_type',
            new_name='document_name',
        ),
        migrations.AlterField(
            model_name='document',
            name='document_name',
            field=models.CharField(max_length=100, verbose_name='Document Name'),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Document Number'),
        ),
        migrations.CreateModel(
            name='DocumentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=documents.models.document_file_upload_path, verbose_name='File')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='documents.document', verbose_name='Document')),
            ],
            options={
                'verbose_name': 'Document File',
                'verbose_name_plural': 'Document Files',
                'ordering': ['created_at'],
            },
        ),
    ]
