# Generated by Django 5.1.4 on 2026-05-28 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_migrate_existing_scanned_copies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='scanned_copy',
        ),
    ]
