# Generated by Django 5.1.4 on 2026-05-28 17:16

import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_remove_document_scanned_copy'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentfile',
            name='error_message',
            field=models.TextField(blank=True, null=True, verbose_name='Error Message'),
        ),
        migrations.AddField(
            model_name='documentfile',
            name='local_tmp_path',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Local Temp Path'),
        ),
        migrations.AddField(
            model_name='documentfile',
            name='upload_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('uploading', 'Uploading'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Upload Status'),
        ),
        migrations.AlterField(
            model_name='documentfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=documents.models.document_file_upload_path, verbose_name='File'),
        ),
    ]
