# Generated by Django 6.1.1 on 2026-10-01 05:56

import django.db.models.deletion
import documents.models.document_renewal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_documentfile_error_message_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Renewal Cost / Expense'),
        ),
        migrations.AddField(
            model_name='document',
            name='is_base_document',
            field=models.BooleanField(default=False, help_text='Base compliance document that cannot be deleted', verbose_name='Is Base Document'),
        ),
        migrations.AddField(
            model_name='document',
            name='valid_from',
            field=models.DateField(blank=True, null=True, verbose_name='Valid From'),
        ),
        migrations.CreateModel(
            name='DocumentRenewal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Document Number')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='Valid From')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='Valid To / Expiry')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Renewal Cost / Expense')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('receipt_file', models.FileField(blank=True, null=True, upload_to=documents.models.document_renewal.renewal_file_upload_path, verbose_name='Receipt / Scanned Copy (Optional)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewals', to='documents.document', verbose_name='Document')),
                ('renewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logged_document_renewals', to=settings.AUTH_USER_MODEL, verbose_name='Renewed By')),
            ],
            options={
                'verbose_name': 'Document Renewal History',
                'verbose_name_plural': 'Document Renewal Histories',
                'ordering': ['-valid_to', '-created_at'],
            },
        ),
    ]
