# Generated by Django 6.1.1 on 2026-10-01 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0012_populate_base_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentfile',
            name='renewal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='documents.documentrenewal', verbose_name='Renewal Record'),
        ),
    ]
