# Generated by Django 5.1.4 on 2026-03-22 11:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
        ('fleet', '0001_initial'),
        ('ledger', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_number', models.CharField(blank=True, max_length=100, unique=True, verbose_name='Trip Number')),
                ('start_odometer', models.PositiveIntegerField(blank=True, null=True, verbose_name='Start Odometer')),
                ('end_odometer', models.PositiveIntegerField(blank=True, null=True, verbose_name='End Odometer')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Trip Date')),
                ('pickup_location', models.CharField(blank=True, max_length=300, verbose_name='Pickup Location')),
                ('pickup_lat', models.DecimalField(blank=True, decimal_places=10, max_digits=18, null=True)),
                ('pickup_lng', models.DecimalField(blank=True, decimal_places=10, max_digits=18, null=True)),
                ('delivery_location', models.CharField(blank=True, max_length=300, verbose_name='Delivery Location')),
                ('delivery_lat', models.DecimalField(blank=True, decimal_places=10, max_digits=18, null=True)),
                ('delivery_lng', models.DecimalField(blank=True, decimal_places=10, max_digits=18, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Load weight in Metric Tons', max_digits=10, null=True, verbose_name='Weight (Tons)')),
                ('rate_per_ton', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Rate per Ton')),
                ('actual_completion_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Actual Completion Date & Time')),
                ('status', models.CharField(choices=[('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='In Progress', max_length=20, verbose_name='Trip Status')),
                ('notes', models.TextField(blank=True, verbose_name='Trip Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_trips', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_trips', to='drivers.driver', verbose_name='Assigned Driver')),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ledger.party', verbose_name='Party')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='fleet.vehicle', verbose_name='Assigned Vehicle')),
            ],
            options={
                'verbose_name': 'Trip',
                'verbose_name_plural': 'Trips',
                'ordering': ['-date', '-created_at'],
                'permissions': [('can_view_all_trips', 'Can view all trips'), ('can_update_trip_status', 'Can update trip status'), ('can_view_driver_dashboard', 'Can access driver dashboard'), ('can_view_manager_dashboard', 'Can access manager dashboard')],
            },
        ),
        migrations.CreateModel(
            name='TripExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Expense Name')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_expenses', to='trips.trip', verbose_name='Trip')),
            ],
            options={
                'verbose_name': 'Trip Expense',
                'verbose_name_plural': 'Trip Expenses',
                'ordering': ['created_at'],
            },
        ),
    ]
