# Generated by Django 5.1.4 on 2026-01-17 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_number', models.CharField(max_length=50, unique=True, verbose_name='Trip Number')),
                ('client_name', models.CharField(max_length=200, verbose_name='Client Name')),
                ('pickup_location', models.CharField(max_length=300, verbose_name='Pickup Location')),
                ('delivery_location', models.CharField(max_length=300, verbose_name='Delivery Location')),
                ('scheduled_datetime', models.DateTimeField(verbose_name='Scheduled Date & Time')),
                ('actual_completion_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Actual Completion Date & Time')),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=20, verbose_name='Trip Status')),
                ('notes', models.TextField(blank=True, verbose_name='Trip Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_trips', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_trips', to=settings.AUTH_USER_MODEL, verbose_name='Assigned Driver')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='fleet.vehicle', verbose_name='Assigned Vehicle')),
            ],
            options={
                'verbose_name': 'Trip',
                'verbose_name_plural': 'Trips',
                'ordering': ['-scheduled_datetime'],
                'permissions': [('can_view_all_trips', 'Can view all trips'), ('can_update_trip_status', 'Can update trip status'), ('can_view_driver_dashboard', 'Can access driver dashboard'), ('can_view_manager_dashboard', 'Can access manager dashboard')],
            },
        ),
    ]
