# Generated by Django 5.1.4 on 2026-01-17 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trip",
            name="client_name",
        ),
        migrations.RemoveField(
            model_name="trip",
            name="delivery_location",
        ),
        migrations.RemoveField(
            model_name="trip",
            name="pickup_location",
        ),
        migrations.AlterField(
            model_name="trip",
            name="trip_number",
            field=models.CharField(
                blank=True, max_length=100, unique=True, verbose_name="Trip Number"
            ),
        ),
        migrations.CreateModel(
            name="TripLeg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "client_name",
                    models.CharField(max_length=200, verbose_name="Client Name"),
                ),
                (
                    "pickup_location",
                    models.CharField(max_length=300, verbose_name="Pickup Location"),
                ),
                (
                    "delivery_location",
                    models.CharField(max_length=300, verbose_name="Delivery Location"),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Load weight in Metric Tons",
                        max_digits=10,
                        null=True,
                        verbose_name="Weight (Tons)",
                    ),
                ),
                (
                    "price_per_ton",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Price per Ton",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="legs",
                        to="trips.trip",
                        verbose_name="Parent Trip",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trip Leg",
                "verbose_name_plural": "Trip Legs",
                "ordering": ["created_at"],
            },
        ),
    ]
