# Generated by Django 5.1.4 on 2026-03-29 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='diesel_liters',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Diesel Liters'),
        ),
        migrations.AddField(
            model_name='trip',
            name='diesel_total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Diesel Total Cost'),
        ),
    ]
