# Generated by Django 5.1.4 on 2026-03-29 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_trip_diesel_liters_trip_diesel_total_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='diesel_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Diesel Rate (Price/Ltr)'),
        ),
    ]
