# Generated by Django 5.1.4 on 2026-01-18 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_remove_trip_client_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ['-created_at'], 'permissions': [('can_view_all_trips', 'Can view all trips'), ('can_update_trip_status', 'Can update trip status'), ('can_view_driver_dashboard', 'Can access driver dashboard'), ('can_view_manager_dashboard', 'Can access manager dashboard')], 'verbose_name': 'Trip', 'verbose_name_plural': 'Trips'},
        ),
        migrations.AlterModelOptions(
            name='tripleg',
            options={'ordering': ['date'], 'verbose_name': 'Trip Leg', 'verbose_name_plural': 'Trip Legs'},
        ),
        migrations.RemoveField(
            model_name='trip',
            name='scheduled_datetime',
        ),
        migrations.AddField(
            model_name='trip',
            name='diesel_expense',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Diesel Expense'),
        ),
        migrations.AddField(
            model_name='trip',
            name='toll_expense',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Toll Expense'),
        ),
        migrations.AddField(
            model_name='tripleg',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date'),
        ),
        migrations.CreateModel(
            name='TripExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Expense Name')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_expenses', to='trips.trip', verbose_name='Trip')),
            ],
            options={
                'verbose_name': 'Trip Expense',
                'verbose_name_plural': 'Trip Expenses',
                'ordering': ['created_at'],
            },
        ),
    ]
