# Generated by Django 5.1.4 on 2026-03-31 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_trip_diesel_rate'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tripexpense',
            unique_together={('trip', 'name')},
        ),
    ]
