# Generated by Django 5.1.4 on 2026-01-18 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_party_remove_financialrecord_associated_trip_leg_and_more'),
        ('trips', '0004_alter_trip_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripleg',
            name='client_name',
        ),
        migrations.AddField(
            model_name='tripleg',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ledger.party', verbose_name='Party'),
        ),
    ]
