# Generated by Django 5.1.4 on 2026-03-31 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_alter_tripexpense_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='revenue_type',
            field=models.CharField(choices=[('per_ton', 'Per Ton'), ('fixed', 'Fixed')], default='per_ton', max_length=10, verbose_name='Revenue Type'),
        ),
    ]
