# Generated by Django 5.1.4 on 2026-01-18 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_remove_tripleg_client_name_tripleg_party'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripleg',
            name='amount_received',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Amount Received'),
        ),
        migrations.AddField(
            model_name='tripleg',
            name='payment_status',
            field=models.CharField(choices=[('Unpaid', 'Unpaid'), ('Partially Paid', 'Partially Paid'), ('Paid', 'Paid')], default='Unpaid', max_length=20, verbose_name='Payment Status'),
        ),
    ]
