# Generated by Django 5.1.4 on 2026-04-11 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_trip_revenue_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ['-date', '-created_at'], 'permissions': [('can_view_all_trips', 'Can view all trips'), ('can_view_driver_dashboard', 'Can access driver dashboard'), ('can_view_manager_dashboard', 'Can access manager dashboard')], 'verbose_name': 'Trip', 'verbose_name_plural': 'Trips'},
        ),
        migrations.RemoveField(
            model_name='trip',
            name='actual_completion_datetime',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='diesel_liters',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='diesel_rate',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='diesel_total_cost',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='end_odometer',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='start_odometer',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='status',
        ),
        migrations.DeleteModel(
            name='TripExpense',
        ),
    ]
