# Generated by Django 5.1.4 on 2026-01-18 11:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0006_remove_financialrecord_associated_legs'),
        ('trips', '0006_tripleg_amount_received_tripleg_payment_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ['-date', '-created_at'], 'permissions': [('can_view_all_trips', 'Can view all trips'), ('can_update_trip_status', 'Can update trip status'), ('can_view_driver_dashboard', 'Can access driver dashboard'), ('can_view_manager_dashboard', 'Can access manager dashboard')], 'verbose_name': 'Trip', 'verbose_name_plural': 'Trips'},
        ),
        migrations.AddField(
            model_name='trip',
            name='amount_received',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Amount Received'),
        ),
        migrations.AddField(
            model_name='trip',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Trip Date'),
        ),
        migrations.AddField(
            model_name='trip',
            name='delivery_location',
            field=models.CharField(blank=True, max_length=300, verbose_name='Delivery Location'),
        ),
        migrations.AddField(
            model_name='trip',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ledger.party', verbose_name='Party'),
        ),
        migrations.AddField(
            model_name='trip',
            name='payment_status',
            field=models.CharField(choices=[('Unpaid', 'Unpaid'), ('Partially Paid', 'Partially Paid'), ('Paid', 'Paid')], default='Unpaid', max_length=20, verbose_name='Payment Status'),
        ),
        migrations.AddField(
            model_name='trip',
            name='pickup_location',
            field=models.CharField(blank=True, max_length=300, verbose_name='Pickup Location'),
        ),
        migrations.AddField(
            model_name='trip',
            name='rate_per_ton',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Rate per Ton'),
        ),
        migrations.AddField(
            model_name='trip',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Load weight in Metric Tons', max_digits=10, null=True, verbose_name='Weight (Tons)'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_trips', to=settings.AUTH_USER_MODEL, verbose_name='Assigned Driver'),
        ),
        migrations.DeleteModel(
            name='TripLeg',
        ),
    ]
