# Generated by Django 5.1.4 on 2026-04-14 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_alter_trip_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='can_be_grouped',
            field=models.BooleanField(default=True, help_text='Whether this trip can be grouped with others in a bill', verbose_name='Can be Grouped'),
        ),
    ]
