# Generated by Django 5.1.4 on 2026-01-18 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0007_alter_trip_options_trip_amount_received_trip_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='amount_received',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='payment_status',
        ),
    ]
