# Generated by Django 5.1.4 on 2026-04-21 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0007_trip_can_be_grouped'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_location', models.CharField(max_length=300, verbose_name='Pickup Location')),
                ('delivery_location', models.CharField(max_length=300, verbose_name='Delivery Location')),
                ('route_type', models.CharField(choices=[('local', 'Local (GST)'), ('intra', 'Intra/Interstate (IGST)')], default='local', max_length=10, verbose_name='Route Type')),
            ],
            options={
                'verbose_name': 'Route',
                'verbose_name_plural': 'Routes',
                'unique_together': {('pickup_location', 'delivery_location', 'route_type')},
            },
        ),
        migrations.AddField(
            model_name='trip',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trips.route', verbose_name='Route'),
        ),
    ]
