# Generated by Django 5.1.4 on 2026-04-25 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0008_route_trip_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='lr_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='LR No'),
        ),
    ]
