# Generated by Django 5.1.4 on 2026-01-19 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0001_initial"),
        ("trips", "0008_remove_trip_amount_received_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="driver_new",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_trips_new",
                to="drivers.driver",
                verbose_name="Assigned Driver (New)",
            ),
        ),
    ]
