# Generated by Django 5.1.4 on 2026-04-29 15:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0005_drivertransaction_drivers_dri_date_f5cc84_idx_and_more'),
        ('fleet', '0010_alter_maintenancerecord_options_and_more'),
        ('ledger', '0026_financialrecord_ledger_fina_date_ea6e31_idx_and_more'),
        ('trips', '0009_trip_lr_no'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['date', 'created_at'], name='trips_trip_date_d60ead_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['vehicle', 'date'], name='trips_trip_vehicle_75520c_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['party', 'date'], name='trips_trip_party_i_fb0ccb_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['driver', 'date'], name='trips_trip_driver__02eda1_idx'),
        ),
    ]
