# Generated by Django 5.1.4 on 2026-01-19 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0001_initial"),
        ("trips", "0010_populate_driver_new"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trip",
            name="driver",
        ),
        migrations.RenameField(
            model_name="trip",
            old_name="driver_new",
            new_name="driver",
        ),
    ]
