# Generated by Django 5.1.4 on 2026-04-30 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0010_trip_trips_trip_date_d60ead_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='gst_type_snapshot',
            field=models.CharField(blank=True, help_text='IGST or GST. Snapshotted from Route at creation.', max_length=10, verbose_name='GST Type (Snapshot)'),
        ),
    ]
