# Generated by Django 5.1.4 on 2026-05-03 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0011_trip_gst_type_snapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='route_type',
            field=models.CharField(choices=[('local', 'Local (GST)'), ('intra', 'Intra/Interstate (IGST)'), ('none', 'Non-GST')], default='local', max_length=10, verbose_name='Route Type'),
        ),
    ]
