# Generated by Django 5.1.4 on 2026-01-19 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0001_initial"),
        ("trips", "0012_migrate_trip_expenses"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trip",
            name="diesel_expense",
        ),
        migrations.RemoveField(
            model_name="trip",
            name="toll_expense",
        ),
        migrations.AlterField(
            model_name="trip",
            name="driver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_trips",
                to="drivers.driver",
                verbose_name="Assigned Driver",
            ),
        ),
    ]
