# Generated by Django 5.1.4 on 2026-05-03 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0028_alter_bill_gst_type'),
        ('trips', '0012_alter_route_route_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='party',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.PROTECT, to='ledger.party', verbose_name='Party'),
        ),
    ]
