# Generated by Django 5.1.4 on 2026-05-03 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0028_alter_bill_gst_type'),
        ('trips', '0013_alter_trip_party'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='default_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Suggested rate for trips on this route', max_digits=10, verbose_name='Default Rate'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledger.party', verbose_name='Party'),
        ),
    ]
