# Generated by Django 5.1.4 on 2026-01-19 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0013_remove_trip_diesel_expense_remove_trip_toll_expense_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="end_odometer",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="End Odometer"
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="start_odometer",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Start Odometer"
            ),
        ),
    ]
