# Generated by Django 5.1.4 on 2026-01-19 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0014_trip_end_odometer_trip_start_odometer'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='delivery_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='delivery_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='pickup_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='pickup_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
