# Generated by Django 5.1.4 on 2026-05-10 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0014_route_default_rate_alter_trip_party'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='amount_received_cached',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Amount Received (Cached)'),
        ),
        migrations.AddField(
            model_name='trip',
            name='gst_amount_cached',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='GST (Cached)'),
        ),
        migrations.AddField(
            model_name='trip',
            name='outstanding_balance_cached',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Outstanding (Cached)'),
        ),
        migrations.AddField(
            model_name='trip',
            name='payment_status_cached',
            field=models.CharField(default='Unpaid', max_length=20, verbose_name='Payment Status (Cached)'),
        ),
        migrations.AddField(
            model_name='trip',
            name='revenue_cached',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Revenue (Cached)'),
        ),
        migrations.AddField(
            model_name='trip',
            name='total_revenue_cached',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Revenue (Cached)'),
        ),
    ]
