# Generated by Django 6.0.7 on 2026-07-18 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0015_trip_amount_received_cached_trip_gst_amount_cached_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='vendor_hire_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount payable to the vendor/owner for attached vehicles', max_digits=12, verbose_name='Vendor Hire Amount'),
        ),
    ]
