# Generated by Django 5.1.4 on 2026-01-19 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0015_trip_delivery_lat_trip_delivery_lng_trip_pickup_lat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='delivery_lat',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='delivery_lng',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='pickup_lat',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='pickup_lng',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=18, null=True),
        ),
    ]
