# Generated by Django 6.0.7 on 2026-09-13 12:32

from datetime import datetime
import zoneinfo
import django.utils.timezone
from django.db import migrations, models


def convert_trip_dates_to_local(apps, schema_editor):
    """
    Convert any existing UTC timestamp strings or datetime objects in trips_trip table
    to the local Asia/Kolkata date (e.g. '2026-07-25') before the column is altered.
    """
    utc = zoneinfo.ZoneInfo('UTC')
    ist = zoneinfo.ZoneInfo('Asia/Kolkata')
    connection = schema_editor.connection
    
    with connection.cursor() as cursor:
        cursor.execute("SELECT id, date FROM trips_trip")
        rows = cursor.fetchall()
        for row_id, date_val in rows:
            if not date_val:
                continue
            if isinstance(date_val, datetime):
                if date_val.tzinfo is None:
                    dt = date_val.replace(tzinfo=utc)
                else:
                    dt = date_val
                local_date = dt.astimezone(ist).date().isoformat()
                cursor.execute("UPDATE trips_trip SET date = %s WHERE id = %s", [local_date, row_id])
            elif isinstance(date_val, str) and (' ' in date_val or 'T' in date_val):
                clean_str = date_val.replace('T', ' ').split('+')[0].split('.')[0]
                try:
                    dt = datetime.strptime(clean_str, '%Y-%m-%d %H:%M:%S').replace(tzinfo=utc)
                    local_date = dt.astimezone(ist).date().isoformat()
                    cursor.execute("UPDATE trips_trip SET date = %s WHERE id = %s", [local_date, row_id])
                except ValueError:
                    pass


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0016_trip_vendor_hire_amount'),
    ]

    operations = [
        migrations.RunPython(convert_trip_dates_to_local, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='trip',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Trip Date'),
        ),
    ]
